### ISSUE TITLE
v0.7.0 release notes version issue

### ISSUE THREAD

**Issue by qiuzhong** [siovene/smarthome-demo#14]
For [v0.7.0](https://github.com/siovene/smart-home-control/releases/tag/v0.7.0), the release notes are confusing:
> \* Verson 0.7.1

The title says the release version is v0.7.0

> \* Upgrade cordova plugin dependency to 0.6.1 (because it has Iotivity 1.1.1)

cordova-plugin-ocf v0.6.1 can't be used for building apks. (see [issue#3](https://github.com/01org/cordova-plugin-ocf/issues/3))

**Comment by siovene** [comment]
Sorry about the mishap. I just released 0.8.0 which fixes this.
