### ISSUE TITLE
No APK for version 0.8.2 (yet)

### ISSUE THREAD

**Issue by ghost** [siovene/smarthome-demo#17]
There isn't an apk for version 0.8.2 yet.

**Comment by siovene** [comment]
Sorry, it looks like I forgot to upload it. Unfortunately I left the office already so this will have to wait about 16-18 hours. Hopefully you can build it yourself if you need it quickly.

**Comment by ghost** [comment]
No worries. I built the package myself.

**Comment by ghost** [comment]
With the version I build, I can't discover any sensors.

**Comment by qiuzhong** [comment]
I built on the app with cordova-plugin-ocf v0.6.4 and it can discover OCF resources.

@uhofemei , please check if the <strong>5683</strong> port is open on the OCF server side.
It's required on Edison and I always open it before launching the OCF server:
```
iptables -A INPUT -p udp --dport 5683 -j ACCEPT
```

**Comment by siovene** [comment]
APK added.

**Comment by ghost** [comment]
Your version works well. Sensor discovery is super fast. Not sure what is different in the version I built, but your APK seems to work OK.
