### ISSUE TITLE
cordova version is too low

### ISSUE THREAD

**Issue by qiuzhong** [siovene/smarthome-demo#3]
In the package.json, the cordova version

```
"cordova": "~4.2.0",
```

is too low. The cordova plugins in package.json cordovaPlugins list will not be installed successfully during executing the command:

```
grunt platform:add:android
```

It doesn't work to install them by manual. (Command hangs and fails to install successfully)

**Comment by siovene** [comment]
Per README instructions, `cordova` in installed globally, so I don't think that package is required at all. I'll see if things work when removing completely.

**Comment by siovene** [comment]
No, that's needed. Will update.
